# Generated by Django 3.1.1 on 2021-02-25 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LabExam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExamDate', models.DateField()),
                ('ExamName', models.CharField(max_length=200)),
                ('ExamDescription', models.TextField()),
                ('TotalMarks', models.FloatField()),
                ('PassMarks', models.FloatField()),
                ('ExamStatus', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'LabExam',
            },
        ),
    ]
